dreamsite/account/urls.py
from django.urls import path

from . import views
from .views import signup_view

app_name = 'account'

urlpatterns = [
    #path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup_view, name='signup'),
]

dreamsite/dreamsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contact/', include('contact.urls')),
    path('', include('dreamjournal.urls')),
    path('account/', include('account.urls', namespace="accounts")), #signup
]

dreamsite/contact/forms.py
from django import forms

class Contact(forms.Form):
    Email = forms.EmailField()

    def __str__(self):
        return self.Email

dreamsite/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.4/css/bootstrap.min.css" 
      integrity="sha512-FOS5ANNUsuvefA5Fm6hZBLsxqfF105LIysEgV8VNz29jZLVYIhI+MOLKPBmMXgkHhARFHf5pE7KbXOLE6TXW0A==" 
      crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="card mt-5 mb-3">
  <!-- <img src="{% static 'img/h20splash.jpg' %}" class="card-img-top" alt="sea with a ship"> -->
  <div class="card-body">
    <h2 class="card-title">About us</h2>
    <p class="card-text"> We are discovering the Developers World and working hard to give to you the most secure and sofisticate trends to improve this application to you, for you with you .....</p> 
    <p>Dream Catcher was created by three Software Developers Students, to allow people to connect deeper with yourself, interact with others with the same interests, and much more.</p>

    <p>Thank you for choose our application as your dreamer keeper we are looking forward to provide the most secure , social and fun application to you!</p>

    <p>Dream Cather is an application where you journal your dreams to keep track and socialize with others around the globe about each other's dreams, while maintaining user privacy</p>

    <p><class="card-text">Very secure and streamline the data access, restrict the user's access and maximize the security of the company and client's data.</p>
    <hr>
    <div class="textabout" style="text-align: left-center">
      <p>"A customer is the most important visitor on our premises, he is not dependent on us.
        <p>We are dependent on him.He is not an interruption in our work.</p>
        <p>He is the purpose of it.He is not an outsider in our business.</p>
        <p>He is part of it.We are not doing him a favor by serving him.</p>
        <p>He is doing us a favor by giving us an opportunity to do so.”</p>
        <p>– Mahatma Gandhi"</p>
        <h4>Enjoy your time with us and keep dreaming!</h4>  
    </div>
   

    <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
  </div>
</div>

{% endblock %}

dreamsite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
   <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge"> -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dream Catcher</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" integrity="undefined" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="undefined" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/0da6f7d6ea.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'base.css' %}">
    <script src="{% static 'script.js' %}" ></script>

    <!-- # About page/contact form style -->
    <style>
      body{
        background-size: cover;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        font-style:italic;
      }
      hr{
        background: white;
      }
      .contact-form{
        background:rgba(0,0,0,.6);
        color:white;
        margin-top: 10em;
        margin-bottom: 100px;
        padding: 20px;
        box-shadow: 0px 0px 10px 3px grey;
      }

      #id_Email {
        color: black;
      }

      .card {
        opacity: 0.7;
        color: black;
      }

      .card img {
        height: 30rem;
      }

      .card-title {

      opacity: 0.9;

      }

      /* .card-title, .card-text {

        opacity: 0.9;

      } */

      /* inbox style */
      .inbox {
        margin-top: 8em;
        margin-left: 15px;
        font-size: 25px;
      }

      .convo {
        margin-top: 5em;
        color: rgb(2, 66, 2);
        font-size: 18px;
        margin-left: auto;
      }

      .convo .backInbox {
        margin-left: 3em;
      }

    </style>
  </head>
  <body id="bg" style="background-image: url({% static '/img/background-dreamcatcher2.jpg' %}); no-repeat center center fixed; -webkit-background-size: cover; -moz-background-size: cover; -o-background-size: cover; background-size: cover;">
  </body>
    <header>
    {% if user.is_authenticated %}
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container-fluid">
          <a class="navbar-brand display-5 ml-6" href="{% url 'home' %}">Dream Catcher</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                  data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                  aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'contact' %}">Contact</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Type</a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'dream' %}">Dream</a></li>
                  <li><a class="dropdown-item" href="{% url 'nightmare' %}">Nightmare</a></li>
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Category
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'reality' %}">Reality</a></li>
                  <li><a class="dropdown-item" href="{% url 'fantasy' %}">Unreal/Fantasy</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link" aria-current="page" href="{% url 'inbox' %}">Inbox</a>
              </li>
            </ul>
            <form class="d-flex" method="POST" action = "{% url 'search' %}">
            {% csrf_token %}
              <input class="form-control me-2" type="search" placeholder="Journal content..." aria-label="Search" name="searched">
              <button class="btn btn-outline-warning" type="submit">Search</button>
            </form>
            <li class="nav-item d-flex">
              <a style="color:white" class="nav-link mr-5" aria-current="page" href="{% url 'logout' %}?next={% url 'home' %}">Logout</a>
            </li>
            <li>
              <a class="navbar-brand" aria-current="page" href="{% url 'profile' user.pk %}">  Hi, {{ user.username }}!</a>
            </li>
          </div>
        </div>
      </nav>
      {% else %}
          <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}">Dream Catcher</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'about' %}">About</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'contact' %}">Contact us</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">Terms&Conditions</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">Type</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'dream' %}">Dream</a></li>
                      <li><a class="dropdown-item" href="{% url 'nightmare' %}">Nightmare</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Category
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'reality' %}">Reality</a></li>
                      <li><a class="dropdown-item" href="{% url 'fantasy' %}">Unreal/Fantasy</a></li>
                    </ul>
                  </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item d-flex">
                    <a class="nav-link" aria-current="page" href="{% url 'account:signup'  %}">Signup</a>
                  </li>
                  <li class="nav-item d-flex">
                    <a class="nav-link" aria-current="page" href="{% url 'login' %}">Login</a>
                  </li>
                </ul>
                  <!-- <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form> -->
              </div>
            </div>
          </nav>
        {% endif %}
    </header>

    <main>
      {% block content %}

      {% endblock %}
    </main>

    <footer class="footer mt-auto py-3 bg-dark fixed-bottom text-light text-center">
      <div class="container">
          <span class="text-muted">©copyright 2021 Dream Catcher, Inc. Designed by JMP Group</span>
      </div>
    </footer>
  </body>
</html>

dreamsite/templates/convo.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
	<div class="row">
		<div style="background-color:black; color:white" class="card col-md-12 mt-5 p-3">
			{% if convo.receiver == request.user %}
				<h3>Conversation with {{ convo.user }}</h3>
			{% else %}
				<h3>Conversation with {{ convo.receiver }}</h3>
			{% endif %}
		</div>
	</div>

	{% if message_list.all.count == 0 %}
	<div class="row my-5">
		<div class="col-md-12">
			<p>No Messages</p>
		</div>
	</div>
	{% endif %}

	{% for message in message_list %}
	<div style="background-color:black" class="row">
		<div class="col-md-12 my-1">
			{% if message.sender == request.user %}
				<div style="background-color:#212529; color:white; border-radius:15px; padding: 10px 0px 3px 10px" class="my-3">
					<p><strong style="color:lightpink">{{ message.sender }}</strong> | {{ message.created_on }}</p>
					<p>{{ message.message }}</p>
				</div>
			{% elif message.recipient == request.user %}
			<div style="background-color:#212529; color:white; border-radius:15px; padding: 10px 0px 3px 10px" class="my-3">
				<p><strong style="color:aquamarine">{{ message.sender }}</strong> | {{ message.created_on }}</p>
				<p>{{ message.message }}</p>
			</div>
			{% endif %}
		</div>
	</div>
	{% endfor %}

	<div class="row">
		<div style="background-color:black" class="card col-md-12 p-3 shadow-sm">
			<form method="POST" action="{% url 'new_message' convo.pk %}">
				{% csrf_token %}
				{{ form.as_p }}

				<div class="d-grid gap-2 mt-3">
					<button class="btn btn-light" type="submit">Send Message</button>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

dreamsite/templates/create_comment.html
{% extends 'base.html' %}

{% block content %}

  {% if user.is_authenticated %}
  <div class="container">
    <div class="row mt-5" style="padding-top: 100px;">
      <h2 class="text-center display-2 mt-4" 
          style="color: white; background-color: transparent;">Your Comment</h2>
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-6 my-5 alert alert-secondary" role="alert">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit" class="bg-primary text-white stretched-link">
          </form>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-10 text-center">
      <h4>Forgot to Log In?</h4>
      <br>
      <h3>Or you can Sign Up to create your own account.</h3>
    </div>
    <div class="col-md-4"></div>
  </div>
  {% endif %}

{% endblock %}

dreamsite/templates/create_post.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}

  <div class="container">
    <div class="row pl-5" style="padding-top: 100px;">
      <div class="col-md-4"></div>
        <div class="col-md-10 my-5 alert alert-secondary" role="alert">
          <h2 class="text-center mt-2">Your latest dream to share..</h2>
          <div class="row pl-5">
              <form method="POST">
                  {% csrf_token %}
                  {{ form.as_p}}
                  <button class='mx-5 mt-3 btn btn-md btn-fill btn-primary'
                          type="submit" value="Submit">
                      <h4 class="text-center">Submit</h4>
                  </button>
              </form>
          </div>        
        </div>
      <div class="col-md-2"></div>
    </div>
  </div>

{% else %}
<h2>You must be logged in to create a post</h2>
{% endif %}
{% endblock %}

dreamsite/templates/delete_post.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
<section class="py-5">
  <div class="container">
    <div class="row pl-5">
      <div class="col-md-4"></div>
      <div class="col-md-10 my-5 alert alert-secondary" role="alert">
        <h2 class="text-center mt-2">Are you sure you want to delete this post?</h2>
        <div class="row pl-5">
            <form method="post">
                {% csrf_token %}
                <button class='mx-5 mt-3 btn btn-md btn-fill btn-primary'
                        type="submit" value="Submit">
                    <h4 class="text-center">Delete</h4>
                </button>
            </form>
        </div>
        <div class="col-md-2"></div>
      </div>
    </div>
  </div>
</section>
{% else %}
<h2>You must be logged in to create a post</h2>
{% endif %}
{% endblock %}

dreamsite/templates/dream.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row" style="background-color: transparent; margin-top: 5rem;">
    <h1 style="color: black; margin-bottom: 2rem;" class="text-center display-3 mt-3">Dreams...</h1>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 ">
      {% for post in journalpost_list %}
      <div class="card mb-4" style="background-image:linear-gradient(to bottom right,{{post.colors_seen}},{{post.colors_seen}}); color:white">
          <div class="card-body" style=" background-color: #212529; border-radius: 0px; margin-bottom:13px; margin-top:13px">
            <a style= "color:white; font-weight:bold; text-decoration:none" href="{% url 'user_detail' post.username_id %}">
            {{ post.username }}</a> | {{ post.created_at}}
              <h2 class="card-title">{{ post.title }}</h2>
              <span>{{ post.category}}   {{ post.type}}</span>
              <p class="card-text">{{post.content|slice:":500" }}</p>
              <a style="color:grey" href="{% url 'post_detail' post.id %}">{{ post.comments.count }} comments</a>
          </div>
      </div>
      <div class="col-md-2"></div>
        {% endfor %}
      </div>
  </div>
</div>
{% endblock %}

dreamsite/templates/fantasy.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row" style="background-color: transparent; margin-top: 5rem;">
    <h1 style="color: black; margin-bottom: 2rem;" class="text-center display-2 mt-3">Fantasy...</h1>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 mt-3 left">
      {% for post in journalpost_list %}
        <div class="card mb-4" style="background-image:linear-gradient(to bottom right,{{post.colors_seen}},{{post.colors_seen}}); color:white">
          <div class="card-body" style=" background-color: #212529; border-radius: 5px; margin-bottom: 10px; margin-top:13px">
            <a style= "color:white; font-weight:bold; text-decoration:none" href="{% url 'user_detail' post.username_id %}">
            {{ post.username }}</a> | {{ post.created_at}}
            <h2 class="card-title">{{ post.title }}</h2>
            <span>{{ post.category}}   {{ post.type}}</span>
            <p class="card-text">{{post.content|slice:":500" }}</p>
            <a style="color:grey" href="{% url 'post_detail' post.id %}">{{ post.comments.count }} comments</a>
          </div>
        </div>
        {% endfor %}
      </div>
    <div class="col-md-4"></div>
  </div>
</div>
{% endblock %}

dreamsite/templates/new_convo.html
{% extends 'base.html' %}

{% block content %}

<div class="convo">
	<div class="row">
		<div class="col-md-12 backInbox">
			<a href="{% url 'inbox' %}" class="btn btn-light">Back to Your Inbox</a>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12 mt-5" style="margin-left: 05ex;">
			<h3>Start a Conversation!</h3>
		</div>
	</div>

	<div class="row mt-3 mb-5" style="margin-left: 05ex;">
		<div class="col-md-5 col-sm-12">
			<form method="POST">
				{% csrf_token %}
				<p>Enter the username for the person you would like to talk to.</p>
				{{ form.as_p }}
				<div class="d-grid gap-2">
					<button class="btn btn-primary mt-4" type="submit" style="font-size: 25px;">Continue</button>
				</div>
			</form>
		</div>
	</div>
</div>

{% endblock %}

dreamsite/templates/nightmare.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row" style="background-color: transparent; margin-top: 5rem;">
    <h1 style="color:black; margin-bottom: 2rem;" class="text-center display-3 mt-3">Nightmares...</h1>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        {% for post in journalpost_list %}
        <div class="card mb-4" style="background-image:linear-gradient(to bottom right,{{post.colors_seen}},{{post.colors_seen}}); color:white">
          <div class="card-body" style=" background-color: #212529; border-radius: 0px; margin-bottom:13px; margin-top:13px">
            <a style= "color:white; font-weight:bold; text-decoration:none" href="{% url 'user_detail' post.username_id %}">
            {{ post.username }}</a> | {{ post.created_at}}
            <h2 class="card-title">{{ post.title }}</h2>
            <span>{{ post.category}}   {{ post.type}}</span>
            <p class="card-text">{{post.content|slice:":500" }}</p>
            <a style="color:grey" href="{% url 'post_detail' post.id %}">{{ post.comments.count }} comments</a>
          </div>
        </div>
        {% endfor %}
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>
{% endblock %}

dreamsite/templates/random_post.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row" style="padding-top: 100px;">

            <div class="card mt-6 bt-6" style="background-image:linear-gradient(to bottom right,{{post.colors_seen}},{{post.colors_seen}}); color:white">
                <div class="card-body" style=" background-color: #212529; border-radius: 0px; margin-bottom:13px; margin-top:13px">
                    <p><a style= "color:white; font-weight:bold; text-decoration:none" class="text-primary" href="{% url 'user_detail' post.username_id %}">
                    @{{ post.username }}</a> | {{ post.created_at}}</p>
                    <h2 class="card-title">{{ post.title }}</h2>
                    <div class="position-relative">
                        <span>{{ post.category}}   {{ post.type}}</span>
                        <p class="card-text pt-5">{{post.content|slice:":500" }}</p>
                        <div class="d-flex flex-row">
                            <a style="color:grey" href="{% url 'post_detail' post.id %}">{{ post.comments.count }} comments</a>
                            <form method="POST" action="{% url 'like' post.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
                                    <div class="ml-5">
                                        <i class="far fa-thumbs-up"><span>{{ post.likes.all.count }}</span></i>
                                    </div>
                                </button>
                            </form>
                            <form method="POST" action="{% url 'dislike' post.id %}">
                                {% csrf_token %}
                                <input type="hidden" name="next" value="{{ request.path }}">
                                <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
                                    <div class="ml-5">
                                        <i class="far fa-thumbs-down"><span>{{ post.dislikes.all.count }}</span></i>
                                    </div>
                                </button>
                            </form>
                            {%if user.id == post.username_id%}
                            <div class="ml-6">
                                <a class="float-left" style="color:grey" href="{% url 'update_post' post.id %}">Edit /</a>
                                <a class="float-left ml-3" style="color:grey" href="{% url 'delete_post' post.id %}">Delete</a>
                            </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
    </div>
    <div class="row">
        <div class="ms-2">
            <a class="nav-link" href="{% url 'create_comment' post.id %}">Add a comment... </a>
        </div>
        <div class="card-body">
            <h2>{{ comments.count }} comments</h2>
            {% for comment in comments %}
            <div class="comments" style="padding: 10px;">
                <a style= "color:gray; font-weight:bold; text-decoration:none"
                    href="{% url 'user_detail' comment.user_id %}">{{ comment.user }}</a> |
                <span class=" text-muted font-weight-normal">{{ comment.created_on }}</span>
                {{ comment.body | linebreaks }}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

dreamsite/templates/reality.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  <div class="row" class="row" style="background-color: transparent; margin-top: 5rem;">
    <h1 style="color:black; margin-bottom: 2rem;" class="text-center display-2 mt-3">Reality...</h1>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8 mt-3">
      {% for post in journalpost_list %}
        <div class="card mb-4" style="background-image:linear-gradient(to bottom right,{{post.colors_seen}},{{post.colors_seen}}); color:white">
          <div class="card-body" style=" background-color: #212529; border-radius: 0px; margin-bottom:13px; margin-top:13px">
            <a style= "color:white; font-weight:bold; text-decoration:none" href="{% url 'user_detail' post.username_id %}">
            {{ post.username }}</a> | {{ post.created_at}}
              <h2 class="card-title">{{ post.title }}</h2>
              <span>{{ post.category}}   {{ post.type}}</span>
              <p class="card-text">{{post.content|slice:":500" }}</p>
              <a style="color:grey" href="{% url 'post_detail' post.id %}">{{ post.comments.count }} comments</a>
          </div>
        </div>     
      {% endfor %}
      <div class="col-md-2"></div>
    </div>
  </div>
</div>
{% endblock %}

dreamsite/templates/terms.html
{% extends 'base.html' %}


{% block content %}

<!-- <div class="textabout" style="text-align: left-center">
    <p>"A customer is the most important visitor on our premises, he is not dependent on us.
      <p>We are dependent on him.He is not an interruption in our work.</p>
      <p>He is the purpose of it.He is not an outsider in our business.</p>
      <p>He is part of it.We are not doing him a favor by serving him.</p>
      <p>He is doing us a favor by giving us an opportunity to do so.”</p>
      <p>– Mahatma Gandhi"</p>
      <h4>Enjoy your time with us and keep dreaming!</h4>  
  </div> -->

{% endblock content %}